#!/bin/bash
#SBATCH -t 6:00:00
#SBATCH -n 1  #total number of tasks, number of nodes calculated automatically
#SBATCH --mem=64G

# ATTENTION: MAKE SURE TO SWITCH THE parseFlag BOOLEAN in stats3d_eco.py TO True BEFORE RUNNING THIS

source ~/.bashrc
conda activate ppaggenv

SPECTRA=~/scripts/pp3d/spectra.py
DIR=`pwd`
ITMIN=0
ITMAX=-1
DT=1
IZMIN=1
IZMAX=80
KLP=4
STORE=TRUE

python $SPECTRA --dir $DIR --itmin $ITMIN --itmax $ITMAX --izmin $IZMIN --izmax $IZMAX --klp $KLP --store
